SEARCH_TYPE_BEGIN_WITH = 1
SEARCH_TYPE_BEGIN_WITH_PHRASE = 3
SEARCH_TYPE_CONTAINS = 4
SEARCH_TYPE_CONTAINS_ANY_WORD = 0
SEARCH_TYPE_END_WITH = 5
SEARCH_TYPE_EXACTLY = 2

OBJECT_TYPE_REPORT_DEFINITION = 3


UPDATE_POLICE_UPSERT = 'Upsert'
